// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohUCieRNpCwy-B69mfzDl10s_4TOuECk',
    appId: '1:268069051984:web:f01730e38a895fba7fbb55',
    messagingSenderId: '268069051984',
    projectId: 'flutter-myshop-65ece',
    authDomain: 'flutter-myshop-65ece.firebaseapp.com',
    databaseURL: 'https://flutter-myshop-65ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-myshop-65ece.appspot.com',
    measurementId: 'G-X1Y476VH3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD79Vs8epLpnz7Jiv9V54zeiN5Lgcgo7p0',
    appId: '1:268069051984:android:85e250e1a0fb79a77fbb55',
    messagingSenderId: '268069051984',
    projectId: 'flutter-myshop-65ece',
    databaseURL: 'https://flutter-myshop-65ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-myshop-65ece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXrVhZ7GU6FRW6U9UU-ZVuThq_ao2Hte4',
    appId: '1:268069051984:ios:5d708d2d39c347097fbb55',
    messagingSenderId: '268069051984',
    projectId: 'flutter-myshop-65ece',
    databaseURL: 'https://flutter-myshop-65ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-myshop-65ece.appspot.com',
    iosClientId: '268069051984-ka3cc5gv32prk7t5ecfpk5417ovn4grj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXrVhZ7GU6FRW6U9UU-ZVuThq_ao2Hte4',
    appId: '1:268069051984:ios:5d708d2d39c347097fbb55',
    messagingSenderId: '268069051984',
    projectId: 'flutter-myshop-65ece',
    databaseURL: 'https://flutter-myshop-65ece-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-myshop-65ece.appspot.com',
    iosClientId: '268069051984-ka3cc5gv32prk7t5ecfpk5417ovn4grj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appchat',
  );
}
